### ISSUE TITLE
Electronics-machine change shall be hinted

### ISSUE THREAD

**Issue by IamIpanda** [zlovred/ZGroupChange#2]
Now in config.ini, when you switch the bob on, _electronic machines_ will be removed from game, but not hinted in notes. There shall be hint.
Then that's my personal point of view. _Electronic machines_ are important quick and small assembling machines used in building in early and middle game. No alternate machines from 5dim or YI mods can exchange it. It shouldn't be removed.

**Comment by zlovred** [comment]
Noted
