### ISSUE TITLE
other.lua:351: Attempt to index field 'entity' (a nil value)

### ISSUE THREAD

**Issue by bigyihsuan** [zlovred/ZGroupChange#3]
Factorio 0.14.1, mod version 1.2.2.
![](http://i.imgur.com/OcnjeLv.png)

**Comment by mcilhargey** [comment]
Can you provide a list of all your installed mods?

**Comment by bigyihsuan** [comment]
![](http://i.imgur.com/ju6iMas.png)

I removed ZGroupChange so that I could begin playing.

**Comment by mcilhargey** [comment]
I'll see about testing a fix tonight

**Comment by bigyihsuan** [comment]
Pretty much same list of mods, same error, different line:
![](http://i.imgur.com/9Hvri2j.png)

**Comment by mcilhargey** [comment]
yep, I'll update this issue when a fix is being pushed - looks like something with flow control and 0.14

**Comment by mcilhargey** [comment]
This should be fixed with 1.2.4. Please verify after release.

**Comment by bigyihsuan** [comment]
Appears to be fixed.
